apiVersion: v1
kind: Service
metadata:
  labels:
    run: postgresql-sqlproxy
  name: postgresql-sqlproxy
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    run: postgresql-sqlproxy